name: Fetch Key Vault Secrets

on:
  workflow_dispatch:
    inputs:
      keyvault_name:
        description: 'Key Vault Name'
        required: true
      tenant_id:
        description: 'Azure Tenant ID'
        required: true
      client_id:
        description: 'Azure Client ID'
        required: true
      client_secret:
        description: 'Azure Client Secret'
        required: true

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Azure PowerShell
        run: Install-Module -Name Az -Scope CurrentUser -Force -AllowClobber

      - name: Fetch Key Vault secrets and push to repo
        shell: pwsh
        run: pwsh ./scripts/migrate-key-vault.ps1
        env:
          KEYVAULT_NAME: ${{ github.event.inputs.keyvault_name }}
          AZURE_TENANT_ID: ${{ github.event.inputs.tenant_id }}
          AZURE_CLIENT_ID: ${{ github.event.inputs.client_id }}
          AZURE_CLIENT_SECRET: ${{ github.event.inputs.client_secret }}
          GITHUB_RUN_ID: ${{ github.run_id }}
